#!/bin/sh

INITPATH=`readlink -f /proc/1/exe`
if [ -z "$INITPATH" ]; then
	# this occurs when the binary has been overwritten.
	# no better way than to try /sbin/init
	# which is not necessarily the best thing to do
	INITPATH=`readlink -f /sbin/init`
fi
INITBIN=`basename "$INITPATH"`
ACTION=`basename "$0"`

case "$INITBIN" in
rund)
	# TODO: write utmp
	case "$ACTION" in
	*halt)
		exec kill -USR1 1
		;;
	*reboot)
		exec kill -INT 1
		;;
	*poweroff|*shutdown)
		exec kill -TERM 1
		;;
	esac
	;;
systemd)
	/bin/systemctl $ACTION "$@"
	;;	
busybox)
	/bin/busybox "$ACTION" "$@"
	;;
sysvinit)
	case "$ACTION" in
	halt|reboot|poweroff)
		/sbin/halt.sysvinit "$@"
		;;
	shutdown)
		/sbin/shutdown.sysvinit "$@"
		;;
	esac
	;;
esac
